-- MySQL Workbench Synchronization
-- Generated: 2020-10-20 21:45
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Mariajo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `stube`  DEFAULT COLLATE utf8mb4_general_ci ;

ALTER TABLE `stube`.`usuaris` 
COLLATE = utf8mb4_general_ci ;

ALTER TABLE `stube`.`videos` 
COLLATE = utf8mb4_general_ci ,
CHANGE COLUMN `id` `id` VARCHAR(100) NOT NULL COMMENT 'id del vídeo, no és AI, però sí UQ' ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
